### ISSUE TITLE
The fate of check-process.sh

### ISSUE THREAD

**Issue by mattyjones** [sensu-plugins/sensu-plugins-process-checks#1]
Should [check-process.sh](https://github.com/sensu/sensu-community-plugins/blob/master/plugins/system/check-process.sh) be written to Ruby, dumped into an 'other lang' gem, or dropped altogether?

I vote to drop it as it is functionally identical to other process check commands and checks written in Ruby should be favored.

**Comment by rmc3** [comment]
@mattyjones IMO, it should be dropped. The Ruby check is more feature rich, and there's no compelling argument I have seen for having checks written in shell, particularly when they duplicate the functionality of native Ruby checks.

An aside, at some point I do want to rewrite [check-process.rb](https://github.com/sensu-plugins/sensu-plugins-process-checks/blob/master/bin/check-process.rb) to use sys-proctable to allow it to be more cross-platform.

**Comment by mattyjones** [comment]
@rmc3 I agree on the sys-proctable idea as well.  I am rewriting the disk and raid checks to use sys-filesystem myself.

**Comment by rmc3** [comment]
With the merge of #7, this is resolved.
