### ISSUE TITLE
Zombie Processes. Critical when no zombie?

### ISSUE THREAD

**Issue by hanynowsky** [sensu-plugins/sensu-plugins-process-checks#13]
```
/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-procs.rb -s Z -w10 -c20
CheckProcess CRITICAL: Found 0 matching processes; state Z
```
In all my sensu clients, I am getting a critical result although the clients have no Zombie processes.
The above command is supposed to Alert when zombie processes number reaches 20 and not the opposite.

Maybe I am getting it all wrong.

**Comment by eheydrick** [comment]
To make this work as the plugin is currently written you need to supply values for critical under and warning under: `check-process.rb -s Z -w 10 -c 20 -C 0 -W 0`. This is because it defaults to alarm when the value is under 1, which it would be when you have no zombies.
