### ISSUE TITLE
Should check-process-restart be written to support more than Debian

### ISSUE THREAD

**Issue by mattyjones** [sensu-plugins/sensu-plugins-process-checks#2]
Should [check-process-restart](https://github.com/sensu/sensu-community-plugins/blob/master/plugins/system/check-process-restart.rb) support more than Debian or is this even possible?

**Comment by rmc3** [comment]
As currently implemented, it's very Debian specific, however it may be possible to similar information from other Linux distributions. Might that be too much feature creep? It'd be a lot of extra logic.

**Comment by mattyjones** [comment]
@rmc3  that fine then what are your thoughts on creating a sensu-plugins-debian repo for it.  My thinking is that if it is Deb specific and will remain so then we have no need for it in a generic repo.  If I want to install disk-checks and I am running Fedora then this is of no use to me.

Is this going to far down the rabbit hole @sensu-plugins/contributors

**Comment by rmc3** [comment]
@mattyjones I agree with creating repositories that host checks which use data sources that are OS/distro specific. We already have sensu-plugins-windows, so there's precedent for it.

**Comment by thecosmicfrog** [comment]
I have added support for Red Hat-based systems and currently have an open pull request for this.

https://github.com/sensu-plugins/sensu-plugins-process-checks/pull/24

**Comment by majormoses** [comment]
@mattyjones any reason to not keep it in the same repo but name the check?

**Comment by majormoses** [comment]
can this be closed? If we want more than debian and epel support my guess would be that someone will contribute it and they can open an issue for that.

**Comment by majormoses** [comment]
Given the lack of interest in this in over a year and the fact that we have debian & epel support which is 90% of the user base I think we should close this and open for individual platforms that we need to add support for rather than keep this open ended issue open forever.
