### ISSUE TITLE
Using sys-proctables for fetching process information cross-platform

### ISSUE THREAD

**Issue by rmc3** [sensu-plugins/sensu-plugins-process-checks#3]
I've been working on a metric check that will output metrics on the number of running processes and threads. We have a need for this to run on at least Windows and Linux. Given this need, it made sense for us to use the [sys-proctable](https://github.com/djberg96/sys-proctable) gem, which provides functionality similar to *nix ```ps``` on platforms including Linux, Windows, BSD, AIX, and HPUX in pure Ruby. I noticed that the [development guidelines](http://sensu-plugins.github.io/development/guidelines.html) mention that using new gems should be avoided where possible.

However, if checks that need to search for processes with certain features or enumerate all processes were to standardize on this gem, it might make it easier to make all of these checks work on multiple platforms.

So, two questions:
1. Would a PR for a new check that uses sys-proctable likely be accepted?
2. Is there interest in refactoring other checks in this repository to use sys-proctable?

**Comment by mattyjones** [comment]
I agree with using this gem.  That directive was more geared to using aws-sdk and fog, pick one and deal.

To your specific goal I think that is a great idea, I am in the process myself of rewriting all disk checks to use the [sys-filesystem](https://github.com/djberg96/sys-filesystem) gem instead of df.  This gem is supposedly cross-platform but I don't own a Windows machine or have access to one to actually verify this yet.

**Comment by rmc3** [comment]
Excellent, thanks for the clarification. I'll submit PRs for the new checks (and possibly other checks refactored to usse sys-proctable) after https://github.com/djberg96/sys-proctable/issues/41 is resolved. There's a new feature required for counting threads per process on Linux that isn't in the most recent gem version.

I have access to several Windows test hosts and I'm happy to help test checks using sys-filesystem.

**Comment by mattyjones** [comment]
@rmc3 cool, the disk-checks repos has some already completed

**Comment by rmc3** [comment]
Slightly off topic, http://www.hurryupandwait.io/blog/in-search-of-a-light-weight-windows-vagrant-box is a great guide to creating a Windows Server 2012 vagrant box. I use a box created from that guide for testing Windows checks.

**Comment by mattyjones** [comment]
@rmc3 Well now...

I will add this link over to GIR for toying with in the vagrantfile as that is the template used to build all the others.

**Comment by djberg96** [comment]
@mattyjones Yes, sys-filesystem is cross platform. It definitely works on Windows.

**Comment by mattyjones** [comment]
@rmc3 Bumped version and created a new release.

Thanks for the work it looks great!  I will try and build this into a gem and stable release into the next few days for all to play with.
