### ISSUE TITLE
Zombies check does not work

### ISSUE THREAD

**Issue by Savemech** [sensu-plugins/sensu-plugins-process-checks#31]
/opt/sensu/embedded/bin/check-process.rb --critical-over 10 --warn-over 1 --state ZOMBIE
CheckProcess CRITICAL: Found 0 matching processes; state ZOMBIE
#:/etc/sensu:2> /opt/sensu/embedded/bin/check-process.rb -s Z -w 5 -c 10
CheckProcess CRITICAL: Found 0 matching processes; state Z
#:/etc/sensu:2> 

both exit codes are 2, which means there is zombies

**Comment by ggenot** [comment]
Replied here : https://github.com/sensu-plugins/sensu-plugins-process-checks/issues/13

Simply add --critical-under 0 and --warn-under 0 as default value are 1

I.ex. : check-process.rb -s Z -w 1 -W 0 -c 10 -C 0

**Comment by Savemech** [comment]
Thanks for help!
