### ISSUE TITLE
Examples to check processes

### ISSUE THREAD

**Issue by 030** [sensu-plugins/sensu-plugins-process-checks#33]
I have read the documentation, but it is not clear to me how to monitor processes. I have tried:

```
/opt/sensu/embedded/bin/check-cmd.rb -c "ps -ef | grep /usr/sbin/mysqld"
```

but that always returns a 0. Could some examples for monitoring processes be added to the Readme?

**Comment by eheydrick** [comment]
You'd want to use `check-process.rb` to check if a process is running. There are a few examples in the [USAGE](https://github.com/sensu-plugins/sensu-plugins-process-checks/blob/master/bin/check-process.rb#L26-L32) section. In your example the command would be `check-process.rb -p /usr/sbin/mysqld -W 1` to warn if the mysqld process isn't running.
