### ISSUE TITLE
check-process.rb --propotional-set-size seems to check CPU utilization

### ISSUE THREAD

**Issue by maoe** [sensu-plugins/sensu-plugins-process-checks#36]
It seems to me that `-P` aka. `--propotional-set-size` checks CPU utilization rather than propotional set size.

**Comment by majormoses** [comment]
@maoe can you please submit a pr to propose a fix?

**Comment by maoe** [comment]
Sorry I don't have the time to make a proper PR but I'd say we just rename the long option name to something like `--cpu-utilization`.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-process-checks/versions/2.0.0
